# Use an official Python runtime as a parent image
FROM hnassiry/aaron-blueocean:1 

# Copy the current directory contents into the container at /app
COPY plugins /var/jenkins_home/plugins
COPY jobs    /var/jenkins_home/jobs
COPY users   /var/jenkins_home/users
